[package]
name = "oneliner"
version = "0.1.0"
authors = ["Marcus Kazmierczak <marcus@mkaz.com>"]
edition = "2021"

[dependencies]
chrono = "0.4.23"
clap = { version = "3.2.23", features = [ "cargo" ] }
serde = { version = "1.0.149", features = ["derive"] }
toml = "0.5.0"
